version: '3.7'

services:
  app:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      REDIRECT_BASE_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:postgres@postgres/accounts
      OIDC_IDP_ISSUER: GOV.UK Accounts
      OIDC_IDP_PRIVATE_KEY_FILE: example-private-key.pem
      OIDC_IDP_SALT: saltsaltsalt
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres

  worker:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "bundle exec sidekiq"
    environment:
      REDIRECT_BASE_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:postgres@postgres/accounts
      OIDC_IDP_ISSUER: GOV.UK Accounts
      OIDC_IDP_PRIVATE_KEY_FILE: example-private-key.pem
      OIDC_IDP_SALT: saltsaltsalt
    volumes:
      - .:/app

  redis:
    image: redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounts
    volumes:
      - accounts_postgres:/var/lib/postgresql/data

volumes:
  accounts_postgres:
