---
default_scopes: []
optional_scopes:
  - openid
  - account_manager_access
  - deanonymise_tokens
  - email
  - transition_checker
hidden_scopes:
  - openid
  - transition_checker
jwt_attributes_and_scopes: {}
