development:
  notify_api_key: <%= ENV['NOTIFY_API_KEY'] %>
  keycloak_client_secret: <%= ENV['KEYCLOAK_CLIENT_SECRET'] %>

production:
  notify_api_key: <%= ENV['NOTIFY_API_KEY'] %>
  keycloak_client_secret: <%= ENV['KEYCLOAK_CLIENT_SECRET'] %>
