---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
resources:
  - name: git-master
    type: git
    icon: github-circle
    source:
      uri: git@github.com:alphagov/govuk-account-manager-prototype.git
      branch: master
      private_key: ((concourse_ci_github_ssh_read_only))

  - name: govuk-slack
    type: slack-notification
    source:
      url: https://hooks.slack.com/((slack_webhook_url))

  - name:  git-master-gems-dockerfile
    icon: github-circle
    type: git
    source:
      uri: git@github.com:alphagov/govuk-account-manager-prototype.git
      branch: master
      private_key: ((concourse_ci_github_ssh_read_only))
      paths:
        - concourse/Dockerfile
        - Gemfile*

  - name: every-day
    type: time
    source:
      interval: 24h

  - name: tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-accounts-manager-tests-image

jobs:
  - name: update-pipeline
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: govuk-account-manager-prototype
        file: git-master/concourse/pipeline.yml

  - name: build-tests-image
    serial: true
    build_log_retention:
      builds: 100
    plan:
      - get: every-day
        trigger: true
      - get: git-master-gems-dockerfile
        trigger: true
      - put: tests-image
        params:
          build: git-master-gems-dockerfile
          dockerfile: git-master-gems-dockerfile/concourse/Dockerfile

  - name: run-quality-checks
    serial: true
    plan:
      - get: tests-image
        passed:
          - build-tests-image
        trigger: true
      - get: git-master
        trigger: true
      - task: run-tests-task
        image: tests-image
        config:
          inputs:
            - name: git-master
          outputs:
            - name: committer-details
          platform: linux
          run:
            dir: git-master
            path: bash
            args:
              - -c
              - |
                set -eu
                service redis-server start
                export RAILS_ENV=test
                bundle install
                bundle exec rake

  - name: deploy-app-staging
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [run-quality-checks]
      - task: deploy-to-paas
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_ORG: govuk_development
          CF_APP_NAME: govuk-account-manager
          CF_SPACE: staging
          CF_STARTUP_TIMEOUT: 15 # minutes
          APP_INSTANCES: 1
          WORKER_INSTANCES: 1
          HOSTNAME: govuk-account-manager-staging
          REQUIRE_BASIC_AUTH: "true"
          BASIC_AUTH_USERNAME: ((basic-auth-username))
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          APP_DOMAIN: www.gov.uk
          WEBSITE_ROOT: https://www.gov.uk
          KEYCLOAK_ADMIN_PASSWORD: ((keycloak-admin-password))
          KEYCLOAK_ADMIN_USER: ((keycloak-admin-user))
          KEYCLOAK_CLIENT_ID: ((keycloak-client-id))
          KEYCLOAK_CLIENT_SECRET: ((keycloak-client-secret))
          KEYCLOAK_REALM_ID: master
          KEYCLOAK_SERVER_URL: https://govuk-keycloak.cloudapps.digital/auth
          KEYCLOAK_REDIRECT_BASE_URL: https://((keycloak-redirect-base-url))
          NOTIFY_API_KEY: ((notify-api-key))
          NOTIFY_TEMPLATE_ID: 6074fdc2-03b3-4bb6-83fe-31220779c13b

  - name: ping-test
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [deploy-app-staging]
      - task: ping-smoke-test
        file: git-master/concourse/tasks/ping-smoke-test.yml
        timeout: 5m
        params:
          URL: 'https://((basic-auth-username)):((basic-auth-password))@govuk-account-manager.cloudapps.digital/register'
          MESSAGE: "Checks that the application deployed to production is not serving HTTP error codes. If this fails, you should investigate immediately."
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Production smoke tests for the GOV.UK Account manager have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
